### ISSUE TITLE
How to make

### ISSUE THREAD

**Issue by RyotaNakajimakun** [khml/sanmoku#1]
I can't make sanmoku .

I am very sad ...

error code 
"make" -f nbproject/Makefile-Debug.mk QMAKE= SUBPROJECTS= .build-conf 
make[1]: ディレクトリ '/home/nakajima/aaa/sanmoku' に入ります
"make"  -f nbproject/Makefile-Debug.mk dist/Debug/GNU-MacOSX/sanmoku
make[2]: ディレクトリ '/home/nakajima/aaa/sanmoku' に入ります
make[2]: *** 'build/Debug/GNU-MacOSX/_ext/247dccd/Board.o' に必要なターゲット '/Users/keiichi/NetBeansProjects/sanmoku/src/Board.cpp' を make するルールがありません.  中止.
make[2]: ディレクトリ '/home/nakajima/aaa/sanmoku' から出ます
nbproject/Makefile-Debug.mk:61: ターゲット '.build-conf' のレシピで失敗しました
make[1]: *** [.build-conf] エラー 2
make[1]: ディレクトリ '/home/nakajima/aaa/sanmoku' から出ます
nbproject/Makefile-impl.mk:39: ターゲット '.build-impl' のレシピで失敗しました
make: *** [.build-impl] エラー 2

**Comment by khml** [comment]
Really sorry.
I fixed this problem and override commits.
So please delete repository you cloned, and clone this repository again.
If it still has something wrong, please write here.
